
# This file is used to configure your Supabase project.
# It's very minimal at the moment and uses default values.
# For full list of options, see the config spec:
# https://supabase.com/docs/guides/self-hosting/config

project_id = "okcbbbjaaytjeslqpbou"

[api]
# Port to use for the API URL.
port = 8080
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. Public and auth schemas are always included.
schemas = ["public", "storage", "auth"]
# Extra schemas to add to the search_path of every request. Note that this doesn't override
# the default search_path that schema. So these schemas will be searched AFTER public and auth.
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure. Limits payload size for accidental
# large queries. Default is 1000.
max_rows = 1000

[api.rate_limits]
# Point where rate limiting kicks in. Default is 1000
points = 1000
# Seconds until points are reset. Default is 1 second
reload_interval = 60

[db]
# Port to use for the local database URL.
port = 5432
# Command to run to start the development database. By default, this is the same as the
# production database. But you could use a different one for local development.
#
# Examples:
#   "docker-compose up postgres -d"
#   "docker restart postgres"
#   "pg_ctl -D ../some/other/database start"
start_cmd = "docker-compose up postgres -d"

[studio]
# Port to use for Supabase Studio.
port = 3000

# Email testing server. Not required, but useful for testing signup and password reset flows locally.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions]
[functions.create-razorpay-order]
verify_jwt = true
[functions.verify-razorpay-payment]
verify_jwt = true
