
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okcbbbjaaytjeslqpbou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rY2JiYmphYXl0amVzbHFwYm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDU5NTUsImV4cCI6MjA1OTMyMTk1NX0.WfKD705sSLec0alQd4mo_G54WlH_-P3NhrahiKylhqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to handle edge function invocation with better error handling
export const invokeFunction = async (name: string, body?: any) => {
  try {
    const { data, error } = await supabase.functions.invoke(name, {
      body,
    });

    if (error) {
      console.error(`Error invoking function ${name}:`, error);
      throw error;
    }

    return { data, error: null };
  } catch (error) {
    console.error(`Exception in function ${name}:`, error);
    return { data: null, error };
  }
};

// Also export as default for backwards compatibility
export default supabase;
