
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxsbinrwflkokyycbvsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c2JpbnJ3Zmxrb2t5eWNidnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDc0NzEsImV4cCI6MjA1OTU4MzQ3MX0.9-DZ5PJAWoAZKX9qVUPAyvpeoDExuIgBKUwxP5Ls4xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to invoke Supabase Edge Functions
export const invokeFunction = async (functionName: string, payload?: any) => {
  const { data, error } = await supabase.functions.invoke(functionName, {
    body: payload
  });
  
  if (error) {
    console.error(`Error invoking function ${functionName}:`, error);
    return { error };
  }
  
  return { data };
};
